server:
  port: 8097
  tomcat:
    accept-count: 10
    max-threads: 10
    max-connections: 20
spring:
  datasource:
    url: jdbc:mysql://10.56.24.66:3306/bcp-auth?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
    max-idle: 4
    max-wait: 1000
    min-idle: 2
    initial-size: 2
  # Specify the DBMS
  jpa:
    database: MYSQL
    # Show or not log for each sql query
    show-sql: true
    # Hibernate ddl auto (create, create-drop, update, validate)
    # hibernate:
      # ddl-auto: validate
      # Naming strategy
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  ldap:
    urls: ldap://10.56.24.65:389
    base: dc=nokia,dc=com
    username: cn=admin,dc=nokia,dc=com
    password: Admin#123
    # user-search-filter=(uid={0})
    user-search-base: ou=people,dc=nokia,dc=com
  redis:
    host: 10.56.24.66
    port: 6379
    # cluster:
    #   nodes: 10.56.24.67:7000,10.56.24.68:7000,10.56.24.69:7000
    database: 0
    timeout: 5000
    pool:
      max-wait: 5000
      max_idle: 4
      min_idle: 1
      max_active: 20
      test-on-create: false
      test-on-borrow: true
      test-on-return: false
      test-while-idle: true
  messages:
    basename: messages/messages
    cache-second: 3600
    encoding: UTF-8
management:
  security:
    enabled: false
